### ISSUE TITLE
Unable to use graphcool out of the box with local deployment

### ISSUE THREAD

**Issue by alvincrespo** [graphcool/framework#1265]
**Current behavior**

When I try to use graphcool in a new installation, I can't seem to get my app going with a local deployment. However, if I select  `shared-eu-west-1` - everything works as expected.

**Reproduction**
```
➜  Desktop graphcool init derpity
Creating a new Graphcool service in derpity... ✔

Written files:
├─ types.graphql
├─ src
│  ├─ hello.js
│  └─ hello.graphql
├─ graphcool.yml
└─ package.json

To get started, cd into the new directory:
  cd derpity

To deploy your Graphcool service:
  graphcool deploy

To start your local Graphcool cluster:
  graphcool local up

To add facebook authentication to your service:
  graphcool add-template auth/facebook

You can find further instructions in the graphcool.yml file,
which is the central project configuration.

➜  Desktop cd derpity
➜  derpity cd derpity
autoenv_cd:chdir:1: no such file or directory: derpity
autoenv_cd:cd:1: no such file or directory: derpity
➜  derpity graphcool loal up
 ▸    loal up is not a graphcool command.
 ▸    Perhaps you meant local up
 ▸    Run graphcool help for a list of available commands.

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
➜  derpity graphcool local up
Running local Graphcool cluster at http://localhost:60000
Running local FaaS runtime at http://localhost:60050
This may take several minutes
$ docker-compose up -d --remove-orphans

docker   local_localfaas_1 is up-to-date
docker   local_graphcool-db_1 is up-to-date
docker   local_graphcool_1 is up-to-date

Waiting for Graphcool to initialize. This can take several minutes... ✔

Success! Cluster local already exists and is up-to-date.
To get started, execute

  $ graphcool init
  $ graphcool deploy

➜  derpity DEBUG=* graphcool deploy
  config CWD /Users/alvincrespo/Desktop/derpity +0ms
  config HOME /Users/alvincrespo +2ms
  config definitionDir /Users/alvincrespo/Desktop/derpity +0ms
  config definitionPath /Users/alvincrespo/Desktop/derpity/graphcool.yml +0ms
  config homepath /Users/alvincrespo/.graphcoolrc +0ms
  config localRCPath /Users/alvincrespo/Desktop/derpity/.graphcoolrc +1ms
  config globalRCPath /Users/alvincrespo/.graphcoolrc +0ms
  cli command id deploy +0ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/alvincrespo/Library/Caches/graphcool/plugins.json +0ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/alvincrespo/Library/Caches/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
  cli-engine:plugins:manager required +296ms
  plugin required command +298ms
  deploy run +0ms
? Please choose the cluster you want to deploy to

local

? Please choose the target name dev
Creating service derpity locally in cluster local...  client choosing clusterEndpoint http://localhost:60000/system +0ms
  client Sending query +0ms
  client       mutation addProject($name: String!, $alias: String, $region: Region, $config: String) {
  client         addProject(input: {
  client           name: $name,
  client           alias: $alias,
  client           region: $region,
  client           clientMutationId: "static"
  client           config: $config
  client         }) {
  client           project {
  client             ...RemoteProject
  client           }
  client         }
  client       }
  client
  client   fragment RemoteProject on Project {
  client     id
  client     name
  client     schema
  client     alias
  client     region
  client     isEjected
  client     projectDefinitionWithFileContent
  client   }
  client
  client        +0ms
  client { name: 'derpity',
  client   alias: undefined,
  client   region: 'EU_WEST_1',
  client   config: '{"modules":[{"name":"","content":"types: ./types.graphql\\n","files":{"./types.graphql":""}}]}' } +1ms
 ✔
  client choosing clusterEndpoint http://localhost:60000/system +1s
  client Sending query +0ms
  client
  client       query ($projectId: ID!){
  client         viewer {
  client           project(id: $projectId) {
  client             ...RemoteProject
  client           }
  client         }
  client       }
  client
  client   fragment RemoteProject on Project {
  client     id
  client     name
  client     schema
  client     alias
  client     region
  client     isEjected
  client     projectDefinitionWithFileContent
  client   }
  client
  client        +0ms
  client { projectId: 'cj9xg08wk00040125983ve1g8' } +0ms
  deploy bundling +6s
  bundler /Users/alvincrespo/Desktop/derpity/.build/build.zip +2ms
Bundling functions...  bundler added files [ '.graphcoolrc',
  'graphcool.yml',
  'package.json',
  'src/',
  'types.graphql',
  '.build/build.zip',
  '.build/dist/',
  'src/hello.graphql' ] +11ms
  ts-builder starting compile [ '/Users/alvincrespo/Desktop/derpity/src/hello.js' ] +1ms
  ts-builder created program +305ms
  ts-builder emitted +245ms
  bundler converted files [ '/Users/alvincrespo/Desktop/derpity/src/hello.js' ] +2ms
  bundler createdFiles [ '/Users/alvincrespo/Desktop/derpity/.build/dist/src/hello.js' ] +0ms
  bundler adding /Users/alvincrespo/Desktop/derpity/.build/dist/src/ src/ +15ms
  bundler adding /Users/alvincrespo/Desktop/derpity/.build/dist/src/byline.js src/byline.js +0ms
  bundler adding /Users/alvincrespo/Desktop/derpity/.build/dist/src/hello-dev.js src/hello-dev.js +0ms
  bundler adding /Users/alvincrespo/Desktop/derpity/.build/dist/src/hello-lambda.js src/hello-lambda.js +0ms
  bundler adding /Users/alvincrespo/Desktop/derpity/.build/dist/src/hello.js src/hello.js +0ms
  bundler added build files [ 'src/',
  'src/byline.js',
  'src/hello-dev.js',
  'src/hello-lambda.js',
  'src/hello.js' ] +0ms
  client choosing clusterEndpoint http://localhost:60000/system +750ms
  client Sending query +0ms
  client
  client       mutation getUrl($projectId: String!) {
  client         getTemporaryDeployUrl(
  client           input: {
  client           projectId: $projectId
  client         }
  client       ) {
  client           url
  client         }
  client       }
  client      +0ms
  client { projectId: 'cj9xg08wk00040125983ve1g8' } +1ms
  bundler uploading to http://localhost:60050/functions/files/cj9xg08wk00040125983ve1g8/cj9xg0ajj000p0125eeu2ft1a +171ms
  bundler {
  bundler   "success" : true
  bundler } +320ms
  bundler bundled 1069 +0ms
 1.1s
  deploy bundled +1ms
Deploying locally...  client
  client
  client Sending service definition: +362ms
  client {
  client   "modules": [
  client     {
  client       "name": "",
  client       "content": "types: ./types.graphql\nfunctions:\n  hello:\n    handler:\n      code: src/hello.js\n    type: resolver\n    schema: src/hello.graphql\npermissions:\n  - operation: '*'\n",
  client       "files": {
  client         "./types.graphql": "# The following types define the data model of the example service\n# based on which the GraphQL API is generated\n\ntype User @model {\n  id: ID! @isUnique\n  name: String\n  dateOfBirth: DateTime\n\n  # Uncomment below - you can declare relations between models like this\n\n  # posts: [Post!]! @relation(name: \"UserPosts\")\n}\n\n\n# Uncomment the model below as well\n\n# type Post @model {\n#   id: ID! @isUnique\n#   title: String!\n#\n#   # Every relation also required a back-relation (to determine 1:1, 1:n or n:m)\n#   author: User! @relation(name: \"UserPosts\")\n# }\n",
  client         "src/hello.graphql": "type HelloPayload {\n  message: String!\n}\n\nextend type Query {\n  hello(name: String): HelloPayload\n}\n"
  client       },
  client       "externalFiles": {
  client         "src/hello.js": {
  client           "url": "http://localhost:60050/functions/files/cj9xg08wk00040125983ve1g8/cj9xg0ajj000p0125eeu2ft1a",
  client           "lambdaHandler": "src/hello-lambda.handle",
  client           "devHandler": "src/hello-dev.js"
  client         }
  client       }
  client     }
  client   ]
  client } +4ms
  client choosing clusterEndpoint http://localhost:60000/system +1ms
  client Sending query +0ms
  client       mutation($projectId: String!, $force: Boolean, $isDryRun: Boolean!, $config: String!) {
  client         push(input: {
  client           projectId: $projectId
  client           force: $force
  client           isDryRun: $isDryRun
  client           config: $config
  client           version: 1
  client         }) {
  client           migrationMessages {
  client             type
  client             action
  client             name
  client             description
  client             subDescriptions {
  client               type
  client               action
  client               name
  client               description
  client             }
  client           }
  client           errors {
  client             description
  client             type
  client             field
  client           }
  client           project {
  client             id
  client             name
  client             alias
  client             projectDefinitionWithFileContent
  client           }
  client         }
  client       }
  client      +0ms
  client { projectId: 'cj9xg08wk00040125983ve1g8',
  client   force: undefined,
  client   isDryRun: false,
  client   config: '{"modules":[{"name":"","content":"types: ./types.graphql\\nfunctions:\\n  hello:\\n    handler:\\n      code: src/hello.js\\n    type: resolver\\n    schema: src/hello.graphql\\npermissions:\\n  - operation: \'*\'\\n","files":{"./types.graphql":"# The following types define the data model of the example service\\n# based on which the GraphQL API is generated\\n\\ntype User @model {\\n  id: ID! @isUnique\\n  name: String\\n  dateOfBirth: DateTime\\n\\n  # Uncomment below - you can declare relations between models like this\\n\\n  # posts: [Post!]! @relation(name: \\"UserPosts\\")\\n}\\n\\n\\n# Uncomment the model below as well\\n\\n# type Post @model {\\n#   id: ID! @isUnique\\n#   title: String!\\n#\\n#   # Every relation also required a back-relation (to determine 1:1, 1:n or n:m)\\n#   author: User! @relation(name: \\"UserPosts\\")\\n# }\\n","src/hello.graphql":"type HelloPayload {\\n  message: String!\\n}\\n\\nextend type Query {\\n  hello(name: String): HelloPayload\\n}\\n"},"externalFiles":{"src/hello.js":{"url":"http://localhost:60050/functions/files/cj9xg08wk00040125983ve1g8/cj9xg0ajj000p0125eeu2ft1a","lambdaHandler":"src/hello-lambda.handle","devHandler":"src/hello-dev.js"}}}]}' } +0ms
  client undefined +1s
 1.3s

Success! Created the following service:

Types

  User
   + A new type with the name `User` is created.
   ├─ +  A new field with the name `name` and type `String` is created.
   └─ +  A new field with the name `dateOfBirth` and type `DateTime` is created.

Resolver Functions

  hello
   + A new resolver function with the name `hello` is created.

Permissions

  Wildcard Permission
   ? The wildcard permission for all operations is added.

Here are your GraphQL Endpoints:

  Simple API:        http://localhost:60000/simple/v1/cj9xg08wk00040125983ve1g8
  Relay API:         http://localhost:60000/relay/v1/cj9xg08wk00040125983ve1g8
  Subscriptions API: ws://localhost:60000/subscriptions/v1/cj9xg08wk00040125983ve1g8
```

![](https://camo.githubusercontent.com/158036cccd6c58c469c977ad2d5776255790c919/68747470733a2f2f61632d73637265656e73686f74732e73332e616d617a6f6e6177732e636f6d2f506c617967726f756e645f2d5f687474706c6f63616c686f7374363030303073696d706c657631636a3976726a336869303030663031323561613130753370345f323031372d31312d31315f31352d30382d30352e6a7067)

**Expected behavior?**

I would expect the local deployment to work as expected from the documentation.

My environment:

```
➜  node -v
v8.7.0
➜  npm -v
5.5.1
➜  docker -v
Docker version 17.09.0-ce, build afdb6d4
➜  graphcool -v
graphcool/0.9.2 (darwin-x64) node-v8.7.0
```

**Comment by alvincrespo** [comment]
I'm curious if anyone else is running into this issue? I can still reproduce easily using 0.10.1 and I'm not sure why. Any help would be greatly appreciated.

**Comment by alvincrespo** [comment]
Here is my updated environment:

```
➜  server node -v
v9.2.0
➜  server npm -v
5.6.0
➜  server graphcool -v
graphcool/0.10.1 (darwin-x64) node-v9.2.0
```

I'm using a local deploy.

**Comment by alvincrespo** [comment]
Here is some more info:

```
➜  server graphcool local ps
Running local Graphcool cluster at http://localhost:60000
Running local FaaS runtime at http://localhost:60050
This may take several minutes
$ docker-compose ps

docker   Name                      Command               State            Ports
docker   ----------------------------------------------------------------------------------------
docker   local_graphcool-db_1   docker-entrypoint.sh mysql ...   Up      3306/tcp
docker   local_graphcool_1      /app/bin/single-server           Up      0.0.0.0:60000->60000/tcp
docker   local_localfaas_1      /app/bin/localfaas               Up      0.0.0.0:60050->60050/tcp
➜  server graphcool logs
2017-12-12T03:56:28.435Z 85ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: Server responded with 400"
}
2017-12-12T03:57:05.686Z 33ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: Server responded with 400"
}
2017-12-12T03:57:25.590Z 8ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: Server responded with 400"
}
2017-12-12T03:57:26.246Z 6ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: Server responded with 400"
}
2017-12-12T03:57:26.384Z 7ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: Server responded with 400"
}
2017-12-12T03:58:45.291Z 33ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: Server responded with 400"
}
➜  server graphcool info

Service Name Cluster / Service ID
──────────── ─────────────────────────────────
server       local/cjb3379lm00040125pszj4i6z

API:           Endpoint:
────────────── ────────────────────────────────────────────────────────────
Simple         http://localhost:60000/simple/v1/cjb3379lm00040125pszj4i6z
Relay          http://localhost:60000/relay/v1/cjb3379lm00040125pszj4i6z
Subscriptions  ws://localhost:60000/subscriptions/v1/cjb3379lm00040125pszj4i6z
File           http://localhost:60000/file/v1/cjb3379lm00040125pszj4i6z
```

**Comment by Melv** [comment]
I've something similar if I deploy (our full project) on `shared-eu-west-1` it works, if I deploy `local` there is always an 
```
2017-12-11T11:49:02.416Z 1228ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: Server responded with 500"
```

message and an other failure message of a function that I can trace.

`graphcool/0.10.1 (linux-x64) node-v6.10.2`

**Comment by alvincrespo** [comment]
Yeah same here. If it's on `local` it doesn't work.

**Comment by marktani** [comment]
Hey I was able to fix my problem as I described here: https://github.com/graphcool/framework/issues/1387#issuecomment-351103913

**Comment by alvincrespo** [comment]
@marktani You rock! That fixed it for me. Does this need to be added to the docs? (e.g. `graphcool local pull`)

I'm more than happy to do that.

**Comment by marktani** [comment]
Hey @alvincrespo, great that this works for you now! 🎉 

`graphcool local up` is already mentioned in the docs: https://www.graph.cool/docs/reference/graphcool-cli/commands-aiteerae6l#local-development-(docker)

It's not part of the ToC yet, looks like an issue there 🤔 

Closing this, please provide a new bug report if you still experience your problem, @Melv, your error is a different one I think 🙂

**Comment by greenietea** [comment]
Hey @Melv, have you been able to resolve your 500 issue yet? I'm experiencing the same problem trying to use auth0.

**Comment by jesstelford** [comment]
For anyone running into this same issue, it appears to be due to the function as a service (faas) not correctly handling errors _that occur outside of the function itself_.

ie;

**This correctly shows an error in `graphcool logs`**

```javascript
export default async () => {
  throw new Error('whoops!');
}
```

```
$ graphcool logs --tail
2018-04-06T06:22:48.858Z 526ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: {\"logs\":[{\"stdout\":\"\"},{\"stderr\":\"\"},{\"error\":\"{\\\"name\\\":\\\"Error\\\",\\\"message\\\":\\\"whoops!\\\",\\\"stack\\\":\\\"Error: whoops!\\\\n    at Object.<anonymous> (/var/faas/functions/.../func.js:2:19)\\\\n    [.. SNIP ..]\\\"}\"}],\"response\":{\"error\":\"Function did not return a valid response. Check your function code / logs.\"}}"
}
```

```
$ docker logs local_localfaas_1 -f
{"stdout":"","stderr":"","error":"{\"name\":\"Error\",\"message\":\"whoops!\",\"stack\":\"Error: whoops!\\n    at Object.<anonymous> (/v
ar/faas/functions/.../func.js:52:19)\\n    [.. SNIP ..]\"}"}
Function invocation summary for project cjfkebttn000401812ew1k8f5 and function twitterAuthentication:
        Duration: 429ms
        Success: false
        Function return value: ''
        Error: '{"name":"Error","message":"whoops!","stack":"Error: whoops!\n    at Object.<anonymous> (/var/faas/functions/.../func.js:52:19)\n    [.. SNIP ..]'
        Process stdout: ''
        Process stderr: ''
```
_(although; the formatting of the error message is quite difficult to read, you can at least find the file & line the error came from. Using `docker logs local_localfaas_1 -f` is more useful IMO)_

**This does not show a useful error**

```javascript
throw new Error('an error outside the function!');
export default async () => {
  return { data: { message: 'success!' } };
}
```

```
$ graphcool logs --tail
018-04-06T06:27:55.830Z 516ms FAILURE {
  "error": "Function returned invalid status code: 0. Raw body: Server responded with 500"
}
```

```
$ docker logs local_localfaas_1 -f
No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
```

## The workaround

Wrap all your code _outside_ the function in a `try/catch`, then only throw the error once inside the function:

```javascript
let topLevelError;
try {
  // any code before the function
} catch (error) {
  topLevelError = error;
}
export default async () => {
  if (topLevelError) {
    throw topLevelError;
  }
  return { data: { message: 'success!' } };
}
```

**Comment by jesstelford** [comment]
I've created a separate issue for the above: https://github.com/graphcool/graphcool-framework/issues/512
