### ISSUE TITLE
Port already used

### ISSUE THREAD

**Issue by tristancaron** [graphcool/framework#1291]
Running `graphcool local up` doesn't work on Mac. Apparently, cannot une the port.

```
$ graphcool local up
  config CWD /Users/tristan/tmp/cool-griffin +0ms
  config HOME /Users/tristan +1ms
  config definitionDir /Users/tristan/tmp/cool-griffin +1ms
  config definitionPath /Users/tristan/tmp/cool-griffin/graphcool.yml +0ms
  config homepath /Users/tristan/.graphcoolrc +0ms
  config localRCPath /Users/tristan/tmp/cool-griffin/.graphcoolrc +0ms
  config globalRCPath /Users/tristan/.graphcoolrc +0ms
  cli command id local:up +0ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/tristan/Library/Caches/graphcool/plugins.json +0ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/tristan/Library/Caches/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
  cli-engine:plugins:manager required +295ms
  plugin required command +297ms
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', 'fe80::10ae:8fc9:3364:9669', '2a01:cb00:16:b400:10e8:15ec:8906:d86c', '2a01:cb00:16:b400:106a:bd80:1d3b:201', '192.168.1.14', '2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7', '2a01:cb00:16:b400:e879:a0d4:6e72:e0a8', '2a01:cb00:16:b400:107f:70a:2997:fe5', 'fe80::dc83:64ff:feaf:610a', 'fe80::8cd4:5aa0:3d16:516a' ] +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +2ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +3ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +1ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::1 +0ms
  portfinder:testPort entered testPort(): trying fe80::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::1 w/ port 60000 with error EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::1:60000
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::1',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +1ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::10ae:8fc9:3364:9669 +0ms
  portfinder:testPort entered testPort(): trying fe80::10ae:8fc9:3364:9669 port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::10ae:8fc9:3364:9669 w/ port 60000 with error EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::10ae:8fc9:3364:9669:60000
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::10ae:8fc9:3364:9669',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +1ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:10e8:15ec:8906:d86c +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:10e8:15ec:8906:d86c port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:10e8:15ec:8906:d86c port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:106a:bd80:1d3b:201 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:106a:bd80:1d3b:201 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:106a:bd80:1d3b:201 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.14 +0ms
  portfinder:testPort entered testPort(): trying 192.168.1.14 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.14 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:107f:70a:2997:fe5 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:107f:70a:2997:fe5 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:107f:70a:2997:fe5 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::dc83:64ff:feaf:610a +0ms
  portfinder:testPort entered testPort(): trying fe80::dc83:64ff:feaf:610a port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::dc83:64ff:feaf:610a w/ port 60000 with error EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +1ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::dc83:64ff:feaf:610a:60000
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::dc83:64ff:feaf:610a',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +0ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:10e8:15ec:8906:d86c +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:10e8:15ec:8906:d86c port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:10e8:15ec:8906:d86c port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:106a:bd80:1d3b:201 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:106a:bd80:1d3b:201 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:106a:bd80:1d3b:201 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.14 +0ms
  portfinder:testPort entered testPort(): trying 192.168.1.14 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.14 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:107f:70a:2997:fe5 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:107f:70a:2997:fe5 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:107f:70a:2997:fe5 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::8cd4:5aa0:3d16:516a +0ms
  portfinder:testPort entered testPort(): trying fe80::8cd4:5aa0:3d16:516a port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::8cd4:5aa0:3d16:516a w/ port 60000 with error EADDRNOTAVAIL +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::8cd4:5aa0:3d16:516a:60000
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::8cd4:5aa0:3d16:516a',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +0ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:10e8:15ec:8906:d86c +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:10e8:15ec:8906:d86c port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:10e8:15ec:8906:d86c port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:106a:bd80:1d3b:201 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:106a:bd80:1d3b:201 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:106a:bd80:1d3b:201 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.14 +1ms
  portfinder:testPort entered testPort(): trying 192.168.1.14 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.14 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:107f:70a:2997:fe5 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:107f:70a:2997:fe5 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:107f:70a:2997:fe5 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() result callback: openPorts is [ 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000 ] +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +0ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60050 +1ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:10e8:15ec:8906:d86c +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:10e8:15ec:8906:d86c port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:10e8:15ec:8906:d86c port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:106a:bd80:1d3b:201 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:106a:bd80:1d3b:201 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:106a:bd80:1d3b:201 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.14 +0ms
  portfinder:testPort entered testPort(): trying 192.168.1.14 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.14 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:ddca:d1e8:4e08:d2c7 port 60050 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:e879:a0d4:6e72:e0a8 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a01:cb00:16:b400:107f:70a:2997:fe5 +0ms
  portfinder:testPort entered testPort(): trying 2a01:cb00:16:b400:107f:70a:2997:fe5 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 2a01:cb00:16:b400:107f:70a:2997:fe5 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() result callback: openPorts is [ 60050, 60050, 60050, 60050, 60050, 60050, 60050, 60050, 60050 ] +0ms
  Docker customVars +0ms
  Docker { PORT: '60000',
  Docker   FUNCTIONS_PORT: '60050',
  Docker   FUNCTION_ENDPOINT_INTERNAL: 'http://localfaas:60050',
  Docker   FUNCTION_ENDPOINT_EXTERNAL: 'http://localhost:60050' } +0ms
Running local Graphcool cluster at http://localhost:60000
Running local FaaS runtime at http://localhost:60050
This may take several minutes
$ docker-compose up -d --remove-orphans

docker   Define and run multi-container applications with Docker.
docker   
docker   Usage:
docker     docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
docker     docker-compose -h|--help
docker   
docker   Options:
docker     -f, --file FILE             Specify an alternate compose file (default: docker-compose.yml)
docker     -p, --project-name NAME     Specify an alternate project name (default: directory name)
docker     --verbose                   Show more output
docker     -v, --version               Print version and exit
docker     -H, --host HOST             Daemon socket to connect to
docker   
docker     --tls                       Use TLS; implied by --tlsverify
docker     --tlscacert CA_PATH         Trust certs signed only by this CA
docker     --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
docker     --tlskey TLS_KEY_PATH       Path to TLS key file
docker     --tlsverify                 Use TLS and verify the remote
docker     --skip-hostname-check       Don't check the daemon's hostname against the name specified
docker                                 in the client certificate (for example if your docker host
docker                                 is an IP address)
docker   
docker   Commands:
docker     build              Build or rebuild services
docker     bundle             Generate a Docker bundle from the Compose file
docker     config             Validate and view the compose file
docker     create             Create services
docker     down               Stop and remove containers, networks, images, and volumes
docker     events             Receive real time events from containers
docker     exec               Execute a command in a running container
docker     help               Get help on a command
docker     kill               Kill containers
docker     logs               View output from containers
docker     pause              Pause services
docker     port               Print the public port for a port binding
docker     ps                 List containers
docker     pull               Pull service images
docker     push               Push service images
docker     restart            Restart services
docker     rm                 Remove stopped containers
docker     run                Run a one-off command
docker     scale              Set number of containers for a service
docker     start              Start services
docker     stop               Stop services
docker     unpause            Unpause services
docker     up                 Create and start containers
docker     version            Show the Docker-Compose version information
1
Exiting with code: 1
```

**Comment by kbrandwijk** [comment]
It seems you have an older version of docker-compose installed.

**Comment by tristancaron** [comment]
It seems you are right. Thank you.
