### ISSUE TITLE
Graphcool on macOS High Sierra

### ISSUE THREAD

**Issue by vincenzo** [graphcool/framework#1333]
Hi, I've so far been working in a Linux VM, but I'd like to move on my Mac (my native host). 

My system:

* macOS High Sierra (10.13.1)
* MBP touch-bar
* Homebrew
* [Fish Shell](https://fishshell.com/)

I installed the following with `brew`

* docker (version 17.10.0-ce, build f4ffd25)
* docker-compose (version 1.17.1, build unknown)
* NodeJS (8.9.1)

I then installed `graphcool` (0.9.2) via `npm`.

**Current problematic behaviour**

I run `gc local up` and I get the following (debug output):

```
$ gc local up 

  config CWD /Users/vincenzo/Drive/Vagrant/zoo/data/graphcool/cms +0ms
  config HOME /Users/vincenzo +2ms
  config definitionDir /Users/vincenzo/Drive/Vagrant/zoo/data/graphcool/cms +0ms
  config definitionPath /Users/vincenzo/Drive/Vagrant/zoo/data/graphcool/cms/graphcool.yml +1ms
  config homepath /Users/vincenzo/.graphcoolrc +0ms
  config localRCPath /Users/vincenzo/Drive/Vagrant/zoo/data/graphcool/cms/.graphcoolrc +0ms
  config globalRCPath /Users/vincenzo/.graphcoolrc +0ms
  cli command id local:up +0ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/vincenzo/Library/Caches/graphcool/plugins.json +0ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/vincenzo/Library/Caches/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
  cli-engine:plugins:manager required +367ms
  plugin required command +370ms
WARNING: Error: Could not find cluster local defined for target loc in /Users/vincenzo/Drive/Vagrant/zoo/data/graphcool/cms/.graphcoolrc.
Please run graphcool local up to start the local cluster.
    at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Output/index.ts:205:41
    at SimpleAction.ActionBase.pause (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Output/actions/ActionBase.ts:65:17)
    at Output.warn (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Output/index.ts:202:17)
    at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Environment.ts:505:14
    at Array.forEach (<anonymous>)
    at Environment.checkClusters (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Environment.ts:496:26)
    at Environment.deserializeRCs (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Environment.ts:490:10)
    at Environment.get [as rc] (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Environment.ts:37:17)
    at Environment.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Environment.ts:436:14)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Environment.js:40:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Environment.js:21:53)
    at fulfilled (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Environment.js:12:58)
    at <anonymous>
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', 'fe80::aede:48ff:fe00:1122', 'fe80::b0:da70:e70:ebb1', '192.168.1.104', 'fdaa:bbcc:ddee:0:823:835a:257f:b5ad', 'fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5', '2a00:23c4:478a:b400:18d0:bed2:d32e:65c0', '2a00:23c4:478a:b400:4986:56fa:72e8:16e1', 'fe80::749d:1eff:fec1:9460', 'fe80::ab67:7c8f:de07:c72b', 'fe80::6316:bfe9:8391:733a' ] +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +3ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +4ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::1 +0ms
  portfinder:testPort entered testPort(): trying fe80::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::1 w/ port 60000 with error EADDRNOTAVAIL +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::1:60000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::1',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +1ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::aede:48ff:fe00:1122 +0ms
  portfinder:testPort entered testPort(): trying fe80::aede:48ff:fe00:1122 port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::aede:48ff:fe00:1122 w/ port 60000 with error EADDRNOTAVAIL +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::aede:48ff:fe00:1122:60000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::aede:48ff:fe00:1122',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +0ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +1ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::b0:da70:e70:ebb1 +0ms
  portfinder:testPort entered testPort(): trying fe80::b0:da70:e70:ebb1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::b0:da70:e70:ebb1 w/ port 60000 with error EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +1ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::b0:da70:e70:ebb1:60000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::b0:da70:e70:ebb1',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +0ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.104 +0ms
  portfinder:testPort entered testPort(): trying 192.168.1.104 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.104 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:823:835a:257f:b5ad +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::749d:1eff:fec1:9460 +0ms
  portfinder:testPort entered testPort(): trying fe80::749d:1eff:fec1:9460 port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::749d:1eff:fec1:9460 w/ port 60000 with error EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::749d:1eff:fec1:9460:60000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::749d:1eff:fec1:9460',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +1ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.104 +0ms
  portfinder:testPort entered testPort(): trying 192.168.1.104 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.104 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:823:835a:257f:b5ad +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60000 +1ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::ab67:7c8f:de07:c72b +0ms
  portfinder:testPort entered testPort(): trying fe80::ab67:7c8f:de07:c72b port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::ab67:7c8f:de07:c72b w/ port 60000 with error EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::ab67:7c8f:de07:c72b:60000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::ab67:7c8f:de07:c72b',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +0ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.104 +0ms
  portfinder:testPort entered testPort(): trying 192.168.1.104 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.104 port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:823:835a:257f:b5ad +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60000 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fe80::6316:bfe9:8391:733a +0ms
  portfinder:testPort entered testPort(): trying fe80::6316:bfe9:8391:733a port 60000 +0ms
  portfinder:testPort done w/ testPort(): failed fe80::6316:bfe9:8391:733a w/ port 60000 with error EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with an err: EADDRNOTAVAIL +0ms
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::6316:bfe9:8391:733a:60000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::6316:bfe9:8391:733a',
  port: 60000 } +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +1ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.104 +1ms
  portfinder:testPort entered testPort(): trying 192.168.1.104 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.104 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:823:835a:257f:b5ad +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60000 +1ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60000 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60000 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60000 +0ms
  portfinder:getPort in eachSeries() result callback: openPorts is [ 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000 ] +1ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +0ms
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +0ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 60050 +1ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.1.104 +0ms
  portfinder:testPort entered testPort(): trying 192.168.1.104 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.1.104 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:823:835a:257f:b5ad +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:823:835a:257f:b5ad port 60050 +1ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 +0ms
  portfinder:testPort entered testPort(): trying fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK fdaa:bbcc:ddee:0:295e:a5b4:9680:4c5 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:18d0:bed2:d32e:65c0 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 +0ms
  portfinder:testPort entered testPort(): trying 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60050 +0ms
  portfinder:testPort done w/ testPort(): OK 2a00:23c4:478a:b400:4986:56fa:72e8:16e1 port 60050 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 60050 +1ms
  portfinder:getPort in eachSeries() result callback: openPorts is [ 60050, 60050, 60050, 60050, 60050, 60050, 60050, 60050 ] +0ms
  Docker customVars +0ms
  Docker { PORT: '60000',
  Docker   FUNCTIONS_PORT: '60050',
  Docker   FUNCTION_ENDPOINT_INTERNAL: 'http://localfaas:60050',
  Docker   FUNCTION_ENDPOINT_EXTERNAL: 'http://localhost:60050' } +0ms
Running local Graphcool cluster at http://localhost:60000
Running local FaaS runtime at http://localhost:60050
This may take several minutes
$ docker-compose up -d --remove-orphans

docker   Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
1
Exiting with code: 1
```

So I run `docker-machine start default` as suggested, but I get this: 

```
$ docker-machine start default

Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
```

And this is the output for `docker-machine ls`: 

```
$ docker-machine ls

NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
```

**Expected behavior?**

It should bring up the docker environment.

**Comment by vincenzo** [comment]
@marktani Open this one here. Eager to get things running on Mac, so if any of you guys has any idea... :)

**Comment by dpetrick** [comment]
* The whole point of docker for mac is _not_ using `docker-machine`. It will still be installed on your system but you can ignore it. Please make sure that you do not have any docker-machine related env vars set in your shell (`env | grep docker` should yield nothing, ideally).
* Make sure that `docker ps` shows something and `docker-machine ls` nothing.
* The docker native installation is (I _think_) only possible via the dmg installer from the docker website. It is likely that you installed docker-toolbox instead of docker native by using homebrew. I'm not a huge fan of installers, but in this case I'd recommend you to uninstall your brew docker and use the installer, then try again, as this likely fixes the issue.

**Comment by vincenzo** [comment]
Thanks for your time @dpetrick. Eventually, it came down to my inexperience with Docker. 
FYI, everything can be installed via `brew`, I just didn't understand that you still need to install the Docker.app to have the Docker daemon running on Mac. It boils down to these: 

```
$ brew update
$ brew install docker docker-compose nodejs
$ brew cask install docker
$ npm install -g graphcool # https://www.graph.cool/docs/quickstart/
```

then making sure to launch the Docker.app

Once that's done, one can use docker as usual from the terminal and `graphcool` works just fine.

**Comment by dpetrick** [comment]
Thanks for the info, good to know that brew is able to install docker for mac as well. You can probably start the docker deamon with brew services to avoid pitfalls like this in the future.
