### ISSUE TITLE
Graphcool local up fails 

### ISSUE THREAD

**Issue by mikerudge** [graphcool/framework#1398]
**Current behavior**
When running `graphcool local up` I get this error

`Running local Graphcool cluster at http://localhost:60000
Running local FaaS runtime at http://localhost:60050
This may take several minutes
$ docker-compose up -d --remove-orphans

Error: spawn docker-compose ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Exiting with code: 1`

After running debug I get this 

` portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::aede:48ff:fe00:1122:60000
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1523:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'EADDRNOTAVAIL',
  code: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: 'fe80::aede:48ff:fe00:1122',
  port: 60000 }`

**Reproduction**
Running macOS 10.13.1
Running version 0.10.1 of graphcool 

I started the project with graphcool init following the quickstart tutorial. 

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**

**Comment by kbrandwijk** [comment]
Do you actually have `docker-compose` installed?

**Comment by mikerudge** [comment]
@kbrandwijk That would make sense ha! 

Solved!
