### ISSUE TITLE
gc local start failing on Windows

### ISSUE THREAD

**Issue by FredyC** [graphcool/framework#1460]
**Current behavior**

```bash
Running local Graphcool cluster at http://localhost:60000
This may take several minutes
$ docker-compose up -d --remove-orphans

docker   Traceback (most recent call last):
docker     File "docker-compose", line 6, in <module>
docker     File "compose\cli\main.py", line 68, in main
docker     File "compose\cli\main.py", line 121, in perform_command
docker     File "compose\cli\main.py", line 938, in up
docker     File "compose\project.py", line 417, in up
docker     File "compose\project.py", line 646, in warn_for_swarm_mode
docker     File "site-packages\docker\api\daemon.py", line 90, in info
docker     File "site-packages\docker\utils\decorators.py", line 46, in inner
docker     File "site-packages\docker\api\client.py", line 189, in _get
docker     File "site-packages\requests\sessions.py", line 488, in get
docker     File "site-packages\requests\sessions.py", line 475, in request
docker     File "site-packages\requests\sessions.py", line 596, in send
docker     File "site-packages\requests\adapters.py", line 423, in send
docker     File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
docker     File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
docker     File "httplib.py", line 1042, in request
docker     File "httplib.py", line 1082, in _send_request
docker     File "httplib.py", line 1038, in endheaders
docker     File "httplib.py", line 882, in _send_output
docker     File "httplib.py", line 844, in send
docker     File "site-packages\docker\transport\npipeconn.py", line 31, in connect
docker     File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
docker     File "site-packages\docker\transport\npipesocket.py", line 50, in connect
docker   pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
docker   Failed to execute script docker-compose
4294967295
Exiting with code: 1
```

**Reproduction**

Initialized a new service with the latest beta. Haven't changed anything in either file.

graphcool/1.0.0-beta2.1.1 (windows-x64) node-v9.3.0

I am quite a rookie with Docker, I am not entirely sure it's properly installed as I had to use some legacy Docker Toolkit due to incompatibility with VirtualBox.

**Comment by kbrandwijk** [comment]
It seems you don't have docker-compose installed. If you use Docker Toolkit then you can only run these commands inside the docker VM it comes with.

**Comment by FredyC** [comment]
Well, I can run `docker` and `docker-compose` from a fresh command line just fine. The Docker VM is started. I tried running something from the docker hub and it's working.

**Comment by marktani** [comment]
Indeed this looks like an issue with your local Docker configuration. Other [issues like this](https://github.com/shipping-docker/php-app/issues/19) could help you figure out a fix.

**Comment by FredyC** [comment]
Ok, I've run it inside Docker Terminal and that works now, but there is apparently some other issue coming from migration/configs. This is probably related to #1451, maybe something else?

```bash
$ docker-compose up -d --remove-orphans

docker   Creating network "localdatabase_graphcool" with driver "bridge"
docker   Creating volume "localdatabase_db-persistence" with default driver
docker   Pulling graphcool-db (mysql:5.7)...
docker   5.7: Pulling from library/mysql
docker   Digest: sha256:1f95a2ba07ea2ee2800ec8ce3b5370ed4754b0a71d9d11c0c35c934e9708dcf1
docker   Status: Downloaded newer image for mysql:5.7
docker   Pulling graphcool-database (graphcool/graphcool-dev:1.0.0-beta2.1)...
docker   1.0.0-beta2.1: Pulling from graphcool/graphcool-dev
docker   Digest: sha256:2fddafd9dbb9912d03d11734cded232fc8b4c943f02af3dcc8191da0f657708e
docker   Status: Downloaded newer image for graphcool/graphcool-dev:1.0.0-beta2.1
docker   Creating localdatabase_graphcool-database_1 ...
docker   Creating localdatabase_graphcool-database_1
docker   Creating graphcool-db ...
Creating localdatabase_graphcool-database_1 ... done
Creating graphcool-db ... done
docker

Waiting for Graphcool to initialize. This can take several minutes... √
 !    'ENOENT': ENOENT: no such file or directory, open 'D:\users\DarkMaster\.graphcool\config.yml'
```
