### ISSUE TITLE
graphcool deploy - JavaScript heap out of memory

### ISSUE THREAD

**Issue by daniele-zurico** [graphcool/framework#999]
OS: Mac Os Sierra
graphcool/0.8.0 (darwin-x64) node-v7.5.0
node --version
v7.5.0
npm --version
5.4.2
Docker-settings: 3GB, 2 CPUs

```
BS-DZurico:~ danielezurico$ graphcool deploy
Bundling functions... ⢿

<--- Last few GCs --->

[79853:0x103000000]    57067 ms: Mark-sweep 1313.6 (1412.2) -> 1313.6 (1412.2) MB, 2342.2 / 4.3 ms  allocation failure GC in old space requested
[79853:0x103000000]    59627 ms: Mark-sweep 1313.6 (1412.2) -> 1313.5 (1368.2) MB, 2559.5 / 3.8 ms  last resort gc 
[79853:0x103000000]    62370 ms: Mark-sweep 1313.5 (1368.2) -> 1313.3 (1368.2) MB, 2743.2 / 13.0 ms  last resort gc 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x907ceac0d39 <JS Object>
    1: inflight [/Users/danielezurico/.nvm/versions/node/v7.5.0/lib/node_modules/graphcool/node_modules/inflight/inflight.js:~7] [pc=0x3cde83c0fc3a](this=0x2dc19f092609 <JS Global Object>,key=0x3bf767d0d2f9 <String[117]\: readdir\x00/Users/danielezurico/Documents/blackswan/app-nest-socialnaut/node_modules/fs-readfile-promise/README.md\x00false>,cb=0x3bf767d0d241 <JS Function f (SharedFunctionInf...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
 5: v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape, v8::internal::Handle<v8::internal::Name> >::EnsureCapacity(v8::internal::Handle<v8::internal::NameDictionary>, int, v8::internal::Handle<v8::internal::Name>, v8::internal::PretenureFlag) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
 6: v8::internal::Dictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape, v8::internal::Handle<v8::internal::Name> >::Add(v8::internal::Handle<v8::internal::NameDictionary>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, int*) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
 7: v8::internal::LookupIterator::ApplyTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
 8: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
 9: v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
10: v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/danielezurico/.nvm/versions/node/v7.5.0/bin/node]
11: 0x3cde833063a7
Abort trap: 6
```
What I'm doing wrong?

**Comment by daniele-zurico** [comment]
Tried with: 
BS-DZurico:~ danielezurico$ node -v
v8.5.0

Same result!

**Comment by daniele-zurico** [comment]
Tried with:
BS-DZurico:~ danielezurico$ node -v
v6.10.2

Same result!

**Comment by dpetrick** [comment]
This is not a docker problem. Your _local_ node is running out of memory. I _think_ because the zip step (_bundling functions_) is failing due to an infinite loop / recursion. Do you have a massive amount of `node_modules` or, in general, function code?

**Comment by daniele-zurico** [comment]
Well not massive, but at that point how I can fix the problem? I don’t think that remove all the node modules is a possible idea.
I use nvm to switch between the different node configurations as you can see from my previous comments.

**Comment by kbrandwijk** [comment]
The recursion might come from how the bundling deals with symlink folders. It resolves them to the actual folder, so in theory, that could lead to recursion.

**Comment by dpetrick** [comment]
What @kbrandwijk said, I don't know enough about node / npm to start troubleshooting, but this is a typical error when zipping is either re-zipping itself over and over or if there are symlinks somewhere.

**Comment by kbrandwijk** [comment]
@daniele-zurico Can you share your package.json, or the dependencies list from it?

**Comment by daniele-zurico** [comment]
Sorry guys but the package.json of what? I’m not deploying my project but I’m just trying to do the self hosting of graphcool following the official documentation.
I’m sorry I forgot to mention that!

**Comment by marktani** [comment]
Can you share the entire content of the folder you're executing this command from? Preferably as a GitHub repository with a `README.md` that describes the reproduction. It looks like you're running in a memory leak when running `graphcool deploy`, which is most likely triggered by a specific situation in your current directory (or further up top the directory tree - but let's check that later).

**Comment by daniele-zurico** [comment]
@marktani of which folder we’re talking?

**Comment by marktani** [comment]
> the folder you're executing this command from

**Comment by daniele-zurico** [comment]
I'm running the commande from my home:
```
BS-DZurico:~ danielezurico$ pwd
/Users/danielezurico
```
But I really don't understand the question. Or I misunderstood the guide or there's something else.
What I want to do is have a self hosting graphcool.

**Comment by daniele-zurico** [comment]
@marktani https://docs-next.graph.cool/reference/deployment/overview-ohs4asd0pe#prerequisites

**Comment by daniele-zurico** [comment]
@marktani Ok got the problem... Installing in the home directory crash everything. I tried to create a folder but now I'm having a new issue:
```
BS-DZurico:test danielezurico$ pwd
/Users/danielezurico/Desktop/test
```
```
BS-DZurico:test danielezurico$ graphcool deploy
? Please choose the cluster you want to deploy to 

local

? Please choose the target name dev
Creating service mgmt-tool locally in cluster local... ✔
Bundling functions... !
 ▸    'ECONNREFUSED': request to http://127.0.0.1:60050/functions/files/cj93cjnqu000b0156hyvrqx7l/cj93cjq4d000w0156inb9v4qa failed, reason: connect ECONNREFUSED
 ▸    127.0.0.1:60050

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

Running with the debug:
```
BS-DZurico:test danielezurico$ graphcool deploy
  config CWD /Users/danielezurico/Desktop/test +0ms
  config HOME /Users/danielezurico +1ms
  config definitionDir /Users/danielezurico/Desktop/test +1ms
  config definitionPath /Users/danielezurico/Desktop/test/graphcool.yml +0ms
  config homepath /Users/danielezurico/.graphcoolrc +0ms
  config localRCPath /Users/danielezurico/Desktop/test/.graphcoolrc +0ms
  config globalRCPath /Users/danielezurico/.graphcoolrc +0ms
  cli command id deploy +0ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/danielezurico/Library/Caches/graphcool/plugins.json +0ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/danielezurico/Library/Caches/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
  cli-engine:plugins:manager required +476ms
  plugin required command +477ms
  deploy run +0ms
  client choosing clusterEndpoint http://localhost:60001/system +0ms
  client Sending query +1ms
  client 
  client       query ($projectId: ID!){
  client         viewer {
  client           project(id: $projectId) {
  client             ...RemoteProject
  client           }
  client         }
  client       }
  client       
  client   fragment RemoteProject on Project {
  client     id
  client     name
  client     schema
  client     alias
  client     region
  client     isEjected
  client     projectDefinitionWithFileContent
  client   }
  client 
  client        +0ms
  client { projectId: 'cj93cjnqu000b0156hyvrqx7l' } +0ms
  deploy bundling +120ms
  bundler /Users/danielezurico/Desktop/test/.build/build.zip +1ms
Bundling functions...  bundler added files [ '.graphcoolrc',
  'graphcool.yml',
  'package.json',
  'src/',
  'types.graphql',
  '.build/build.zip',
  '.build/dist/',
  'src/hello.graphql' ] +16ms
  ts-builder starting compile [ '/Users/danielezurico/Desktop/test/src/hello.js' ] +1ms
  ts-builder created program +172ms
  ts-builder emitted +194ms
  bundler converted files [ '/Users/danielezurico/Desktop/test/src/hello.js' ] +2ms
  bundler createdFiles [ '/Users/danielezurico/Desktop/test/.build/dist/src/hello.js' ] +0ms
  bundler adding /Users/danielezurico/Desktop/test/.build/dist/src/ src/ +13ms
  bundler adding /Users/danielezurico/Desktop/test/.build/dist/src/byline.js src/byline.js +0ms
  bundler adding /Users/danielezurico/Desktop/test/.build/dist/src/hello-dev.js src/hello-dev.js +0ms
  bundler adding /Users/danielezurico/Desktop/test/.build/dist/src/hello-lambda.js src/hello-lambda.js +0ms
  bundler adding /Users/danielezurico/Desktop/test/.build/dist/src/hello.js src/hello.js +0ms
  bundler added build files [ 'src/',
  'src/byline.js',
  'src/hello-dev.js',
  'src/hello-lambda.js',
  'src/hello.js' ] +0ms
  client choosing clusterEndpoint http://localhost:60001/system +634ms
  client Sending query +0ms
  client 
  client       mutation getUrl($projectId: String!) {
  client         getTemporaryDeployUrl(
  client           input: {
  client           projectId: $projectId
  client         }
  client       ) {
  client           url
  client         }
  client       }
  client      +0ms
  client { projectId: 'cj93cjnqu000b0156hyvrqx7l' } +0ms
  bundler uploading to http://127.0.0.1:60050/functions/files/cj93cjnqu000b0156hyvrqx7l/cj93cm7yq000z0156d9zxglru +181ms
 !
FetchError: request to http://127.0.0.1:60050/functions/files/cj93cjnqu000b0156hyvrqx7l/cj93cm7yq000z0156d9zxglru failed, reason: connect ECONNREFUSED 127.0.0.1:60050
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Exiting with code: 1
````

**Comment by kbrandwijk** [comment]
Did you run `graphcool local up` first to start the Docker instances?

**Comment by daniele-zurico** [comment]
@kbrandwijk this is the step performed:
1) graphcool init
2) graphcool local up
3) graphcool init
```
BS-DZurico:graph-local danielezurico$ graphcool init
  config CWD /Users/danielezurico/Desktop/graph-local +0ms
  config HOME /Users/danielezurico +3ms
  config definitionDir /Users/danielezurico/Desktop/graph-local +0ms
  config definitionPath /Users/danielezurico/Desktop/graph-local/graphcool.yml +0ms
  config homepath /Users/danielezurico/.graphcoolrc +1ms
  config localRCPath /Users/danielezurico/Desktop/graph-local/.graphcoolrc +0ms
  config globalRCPath /Users/danielezurico/.graphcoolrc +0ms
  cli command id init +0ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/danielezurico/Library/Caches/graphcool/plugins.json +0ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/danielezurico/Library/Caches/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
  cli-engine:plugins:manager required +391ms
  plugin required command +394ms

The directory /Users/danielezurico/Desktop/graph-local contains files that could conflict:

  graphcool.yml
  package.json
  src
  types.graphql

Either try using a new directory name, or remove the files listed above.

NOTE: The behavior of the init command changed, to deploy a project, please use graphcool deploy

To force the init process in this folder, use graphcool init --force
Exiting with code: 1
```
4) graphcool init --force
5) graphcool deploy 
Finally I got success!!!!

**Comment by daniele-zurico** [comment]
@kbrandwijk @marktani we can close the ticket.... Probably the guide should say that you need to create a folder and then continue.
Last question after I setup everything there's a way to access to a console? like: https://console.graph.cool/ but on your local environment
